[package]
name = "multicaster"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.26.2"
once_cell = "1.17.2"
serde = { version = "1.0.163", features = ["derive"] }
socket2 = "0.5.3"
toml = "0.7.4"
